# Site settings
title: Flaschenpost
author: David Joaqu√≠n Shourabi Porcel
baseurl: "/flaschenpost"
url: "https://www.davidjsp.eu"
email: 'david@davidjsp.eu'
launchdate: 2018-05-07

# Build settings
strict_front_matter: true
compress_html:
    clippings: all
    comments: all
sass:
    style: compressed
plugins:
    - jekyll-feed
    - jekyll-sitemap

permalink: /posts/:title

defaults:
    -
        scope:
            path: "about"
        values:
            layout: "about"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

exclude:
    - TODO.md
